services:
  base:
    hostname: devlab
    image: devlab-base
    build:
      context: .
      dockerfile: docker/base/Dockerfile
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        DEBIAN_MIRROR: ${DEBIAN_MIRROR}
    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    command: sleep infinity

  python:
    image: devlab-python

    build:
      context: .
      dockerfile: docker/python/Dockerfile

    hostname: python

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    command: sleep infinity

  go:
    image: devlab-go

    build:
      context: .
      dockerfile: docker/go/Dockerfile

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    command: sleep infinity

  rust:
    image: devlab-rust

    build:
      context: .
      dockerfile: docker/rust/Dockerfile

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    command: sleep infinity

  node:
    image: devlab-node

    build:
      context: .
      dockerfile: docker/node/Dockerfile

    volumes:
      - .:/workspace

    stdin_open: true
    tty: true

    command: sleep infinity
